### PR TITLE
WHAT IF WE REMOVED WEBFONTS?

### PR DESCRIPTION
**Pull request by allypalanzi**
🤔 

**Before**

before

**After**

after

### CODE REVIEW

**Comment by wnstn** [comment]
it looks the same :trollface:

**Comment by allypalanzi** [comment]
not gonna merge this until i get input from a designer: cc @ssktanaka @kelseyscherer

**Comment by kelseyscherer** [comment]
:+1: Some time in the future I want to clean up line-height and spacing, but not today.

**Comment by reimertz** [comment]
I luled.

**Pull request merged**
